/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "typedefine.h"
#include "app_t5l_ctrl.h"
#include "app_t5l_cfg.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

//=====================================================================================================================
//屏幕的描述指针地址范围：
//0x9010~0x9100：托盘重量
//0x9110~0x9160：帮助信息
//0x9210~0x9300：托盘序号
//0x9310~0x9400：托盘背景色
//=====================================================================================================================

INT16 ES_WeightVlu_DP_Add[T5L_MAX_CHANEL_LEN]  ={0x9011,0x9021,0x9031,0x9041,0x9051,0x9061,0x9071,0x9081,0x9091,0x90A1,0x90B1,0x90C1,0x90D1,0x90E1,0x90F1,0x9101};
INT16 ES_HelpVlu_DP_Add[T5L_MAX_CHANEL_LEN]    ={0x9111,0x9121,0x9131,0x9141,0x9151,0x9161,0x9171,0x9181,0x9191,0x91A1,0x91B1,0x91C1,0x91D1,0x91E1,0x91F1,0x9201};
INT16 ES_WeightIndex_DP_Add[T5L_MAX_CHANEL_LEN]={0x9211,0x9221,0x9231,0x9241,0x9251,0x9261,0x9271,0x9281,0x9291,0x92A1,0x92B1,0x92C1,0x92D1,0x92E1,0x92F1,0x9301};
INT16 ES_WeightColor_DP_Add[T5L_MAX_CHANEL_LEN]={0x9311,0x9321,0x9331,0x9341,0x9351,0x9361,0x9371,0x9381,0x9391,0x93A1,0x93B1,0x93C1,0x93D1,0x93E1,0x93F1,0x9401};

//=====================================================================================================================
//=============================================[8头]===[1.托盘重量的描述指针]============================================
//=====================================================================================================================
//托盘的重量显示：不带小数点显示
//                              左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_VLU_DIS_X(I) 	(43  + I*(325) + I/1*12     +(I/4)*0)//X position
#define L8_WEIGHT_VLU_DIS_Y(I) 	(183 + I*(180) + (I/1)*12   + 0)//Y position
#define L8_WEIGHT_VLU_DIS_COLOR	(0x6474)//蓝色(0x041F)//color
#define L8_WEIGHT_VLU_DIS_SIZE	(0x0040)//字库(00:0号字库)+字体大小(20:32大小)
#define L8_WEIGHT_VLU_DIS_DQZWS	(0x0204)//对齐(00:左对齐，01:右对齐，02:居中) + 整数位数(04:4位整数)
#define L8_WEIGHT_VLU_DIS_XWSLX	(0x0001)//小数位数(00:无小数，01:1位小数)+变量类型(01:长整型4字节)
appScreenDpCfg_Type ES_8H_WeightVlue_DP_Vlu_WuXiaoShu[8]=
{
//  x    					y      					颜色      				字库+字体大小			 对齐+整数位数    			   小数位数 变量类型
	{L8_WEIGHT_VLU_DIS_X(0),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(0),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(1),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(1),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(2),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(2),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(3),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(3),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
};
//托盘的重量显示：带小数点显示
//                              	左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_VLU_DIS_XS_X(I) 	(46  + I*(325) + I/1*12     +(I/4)*0)//X position
#define L8_WEIGHT_VLU_DIS_XS_Y(I) 	(197 + I*(180) + (I/1)*12   + 0)//Y position
#define L8_WEIGHT_VLU_DIS_XS_COLOR	(0x6474)//颜色
#define L8_WEIGHT_VLU_DIS_XS_SIZE	(0x0028)//字库+字体大小
#define L8_WEIGHT_VLU_DIS_XS_DQZWS	(0x0204)//对齐+整数位数
#define L8_WEIGHT_VLU_DIS_XS_XWSLX	(0x0101)//小数位数+变量类型
appScreenDpCfg_Type ES_8H_WeightVlue_DP_Vlu_YouXiaoShu[8]=
{
//  x    					y      						颜色      				  字库+字体大小				 对齐+整数位数    			  小数位数 变量类型
	{L8_WEIGHT_VLU_DIS_XS_X(0),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(0),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(1),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(1),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(2),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(2),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(3),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(3),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
};


//=====================================================================================================================
//=========================================[8头]===[2.帮助信息的描述指针]================================================
//=====================================================================================================================
//帮助信息：不带小数点显示
//                              左边框 	单个宽度   	   单个间距	  	  (8+8)分块间距
#define L8_HELP_VLU_DIS_X(I) 	(0  + (I%3)*(100) 	+ (I%3)/2*60    +(I/3)*443)//X
#define L8_HELP_VLU_DIS_Y(I) 	(552 + I*(85) + (I/1)*(15)   	+ 0)//Y
#define L8_HELP_VLU_DIS_COLOR	(0xF810)//差值颜色
#define L8_HELP_VLU_DIS_COLOR_S	(0x0000)//被减数序号颜色
#define L8_HELP_VLU_DIS_COLOR_S2 (0x041F)//减数序号颜色
#define L8_HELP_VLU_DIS_SIZE	(0x0022)//字库+字体大小
#define L8_HELP_VLU_DIS_DQZWS	(0x0204)//对齐+整数位数
#define L8_HELP_VLU_DIS_XWSLX	(0x0000)//小数位数+变量类型
appScreenDpCfg_Type ES_8H_HelpVlue_DP_Vlu_WuXiaoShu[12]=
{
//  x    					y      					颜色      				字库+字体大小			  对齐+整数位数    		  小数位数 变量类型
	{L8_HELP_VLU_DIS_X(0),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(1),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(2),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(0),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(1),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(2),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(3),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(4),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(5),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(3),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(4),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(5),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
};

//帮助信息：带小数点显示
//                              	左边框 	单个宽度   	   单个间距	  	  (8+8)分块间距
#define L8_HELP_VLU_DIS_XS_X(I) 	(5  +  (I%6==1)*110 + (I%6==2)*250 + (I%6==3)*450 + (I%6==4)*560 + (I%6==5)*700)
#define L8_HELP_VLU_DIS_XS_Y(I) 	(552 + I*(85) + (I/1)*(15)   	+ 0)//Y
#define L8_HELP_VLU_DIS_XS_COLOR	(0xF810)//差值颜色
#define L8_HELP_VLU_DIS_XS_COLOR_S	(0x0000)//被减数序号颜色
#define L8_HELP_VLU_DIS_XS_COLOR_S2 (0x041F)//减数序号颜色
#define L8_HELP_VLU_DIS_XS_SIZE		(0x001C)//字库+字体大小
#define L8_HELP_VLU_DIS_XS_SIZE_S	(0x001C)//字库+字体大小
#define L8_HELP_VLU_DIS_XS_DQZWS	(0x0204)//对齐+整数位数
#define L8_HELP_VLU_DIS_XS_XWSLX1	(0x0000)//小数位数+变量类型
#define L8_HELP_VLU_DIS_XS_XWSLX	(0x0100)//小数位数+变量类型
appScreenDpCfg_Type ES_8H_HelpVlue_DP_Vlu_YouXiaoShu[12]=
{
//  x    					y      					颜色      				字库+字体大小			  对齐+整数位数    		  小数位数 变量类型
	{L8_HELP_VLU_DIS_XS_X(0),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(1),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(2),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
	{L8_HELP_VLU_DIS_XS_X(0),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(1),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(2),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
	{L8_HELP_VLU_DIS_XS_X(3),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(4),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(5),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
	{L8_HELP_VLU_DIS_XS_X(3),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(4),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(5),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
};


//=====================================================================================================================
//=========================================[8头]===[3.托盘序号的描述指针]================================================
//=====================================================================================================================
//                              		左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_VLU_INDEX_DIS_X(I) 	(160  + I*(325) + I/1*12     +(I/4)*0)//X
#define L8_WEIGHT_VLU_INDEX_DIS_Y(I) 	(139 + I*(180) + (I/1)*12   + 0)//Y
#define L8_WEIGHT_VLU_INDEX_DIS_COLOR	(0x0000)//颜色0x6494
#define L8_WEIGHT_VLU_INDEX_DIS_SIZE	(0x0012)//字库+字体大小
#define L8_WEIGHT_VLU_INDEX_DIS_DQZWS	(0x0202)//对齐+整数位数
#define L8_WEIGHT_VLU_INDEX_DIS_XWSLX	(0x0000)//小数位数+变量类型
appScreenDpCfg_Type ES_8H_WeightIndex_DP_Vlu[8]=
{
//  x    							y      							颜色      						字库+字体大小					 对齐+整数位数    				  小数位数 变量类型(00:整数2字节，01:长整数4字节)
	{L8_WEIGHT_VLU_INDEX_DIS_X(0),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(0),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(1),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(1),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(2),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(2),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(3),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(3),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
};


//=====================================================================================================================
//=========================================[8头]===[4.托盘背景色的描述指针]==============================================
//=====================================================================================================================
//                              	左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_COLOR_DIS_X(I) 	(16 + I*(325) + I/1*12 	 +(I/4)*0)//X
#define L8_WEIGHT_COLOR_DIS_Y(I) 	(126 + I*(180) + (I/1)*12 + 0)//Y
appScreenDpColorCfg_Type ES_8H_WeightColor_DP_Vlu[8]=
{
//  x    						y      					   	
	{L8_WEIGHT_COLOR_DIS_X(0),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(0),	L8_WEIGHT_COLOR_DIS_Y(1)},
	{L8_WEIGHT_COLOR_DIS_X(1),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(1),	L8_WEIGHT_COLOR_DIS_Y(1)},
	{L8_WEIGHT_COLOR_DIS_X(2),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(2),	L8_WEIGHT_COLOR_DIS_Y(1)},
	{L8_WEIGHT_COLOR_DIS_X(3),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(3),	L8_WEIGHT_COLOR_DIS_Y(1)},
};





//=====================================================================================================================
//============================================[16头]===[1.托盘重量的描述指针]============================================
//=====================================================================================================================
//托盘的重量显示：不带小数点显示
//                              左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_VLU_DIS_X(I) 	(19  + I*(150) + I/1*18     +(I/4)*18)//X position
#define L_WEIGHT_VLU_DIS_Y(I) 	(200 + I*(210) + (I/1)*31   + 0)//Y position
#define L_WEIGHT_VLU_DIS_COLOR	(0x6474)//color
#define L_WEIGHT_VLU_DIS_SIZE	(0x0020)//字库(00:0号字库)+字体大小(20:32大小)
#define L_WEIGHT_VLU_DIS_DQZWS	(0x0204)//对齐(00:左对齐，01:右对齐，02:居中) + 整数位数(04:4位整数)
#define L_WEIGHT_VLU_DIS_XWSLX	(0x0001)//小数位数(00:无小数，01:1位小数)+变量类型(01:长整型4字节)
appScreenDpCfg_Type ES_16H_WeightVlue_DP_Vlu_WuXiaoShu[16]=
{
//  x坐标    				y坐标      				 背景颜色      			 字库+字体大小			  对齐+整数位数    			   小数位数+变量类型
	{L_WEIGHT_VLU_DIS_X(0),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(0),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(1),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(1),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(2),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(2),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(3),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(3),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(4),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(4),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(5),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(5),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(6),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(6),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(7),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(7),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
};
//托盘的重量显示：带小数点显示
//                              左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_VLU_DIS_XS_X(I) 	(19  + I*(150) + I/1*18     +(I/4)*18)//X position
#define L_WEIGHT_VLU_DIS_XS_Y(I) 	(200 + I*(210) + (I/1)*31   + 0)//Y position
#define L_WEIGHT_VLU_DIS_XS_COLOR	(0x6474)//颜色
#define L_WEIGHT_VLU_DIS_XS_SIZE	(0x0032)//字库+字体大小
#define L_WEIGHT_VLU_DIS_XS_DQZWS	(0x0204)//对齐+整数位数
#define L_WEIGHT_VLU_DIS_XS_XWSLX	(0x0101)//小数位数+变量类型
appScreenDpCfg_Type ES_16H_WeightVlue_DP_Vlu_YouXiaoShu[16]=
{
//  x坐标    				y坐标      				     背景颜色      			   字库+字体大小			  对齐+整数位数    			   小数位数+变量类型
	{L_WEIGHT_VLU_DIS_XS_X(0),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(0),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(1),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(1),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(2),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(2),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(3),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(3),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(4),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(4),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(5),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(5),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(6),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(6),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(7),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(7),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
};

//=====================================================================================================================
//========================================[16头]===[2.帮助信息的描述指针]================================================
//帮助信息：不带小数点显示
//                              左边框 	单个宽度   	   单个间距	  	  (8+8)分块间距
#define L_HELP_VLU_DIS_X(I) 	(310  + I*(430-12) 	+ I/1*0     	+(I/4)*0)//X
#define L_HELP_VLU_DIS_Y(I) 	(575  + I*(637-571) + (I/3)*(15)   	+ 0)//Y
#define L_HELP_VLU_DIS_COLOR	(0xF810)//颜色
#define L_HELP_VLU_DIS_SIZE		(0x001A)//字库+字体大小
#define L_HELP_VLU_DIS_DQZWS	(0x0204)//对齐+整数位数
#define L_HELP_VLU_DIS_XWSLX	(0x0002)//小数位数+变量类型
appScreenDpCfg_Type ES_16H_HelpVlue_DP_Vlu_WuXiaoShu[6]=
{
//  x坐标    				y坐标      				 背景颜色      			 字库+字体大小			  对齐+整数位数    			小数位数+变量类型
	{L_HELP_VLU_DIS_X(0),	L_HELP_VLU_DIS_Y(0),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(0),	L_HELP_VLU_DIS_Y(1),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(0),	L_HELP_VLU_DIS_Y(2),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(1),	L_HELP_VLU_DIS_Y(0),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(1),	L_HELP_VLU_DIS_Y(1),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(1),	L_HELP_VLU_DIS_Y(2),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
};

//帮助信息：带小数点显示
#define L_HELP_VLU_DIS_XS_X(I) 	(I*(450+18)+28)//X
#define L_HELP_VLU_DIS_XS_Y(I) 	(I*(500+18)+118)//Y
#define L_HELP_VLU_DIS_XS_COLOR	(0x6474)//颜色
#define L_HELP_VLU_DIS_XS_SIZE	(0x0010)//字库+字体大小
#define L_HELP_VLU_DIS_XS_DQZWS	(0x0202)//对齐+整数位数
#define L_HELP_VLU_DIS_XS_XWSLX	(0x0002)//小数位数+变量类型
appScreenDpCfg_Type ES_16H_HelpVlue_DP_Vlu_YouXiaoShu[6]=
{
//  x坐标    					y坐标      				 背景颜色      			 	 字库+字体大小			  对齐+整数位数    			   小数位数+变量类型
	{L_HELP_VLU_DIS_XS_X(0),	L_HELP_VLU_DIS_XS_Y(0),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(0),	L_HELP_VLU_DIS_XS_Y(1),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(0),	L_HELP_VLU_DIS_XS_Y(2),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(1),	L_HELP_VLU_DIS_XS_Y(0),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(1),	L_HELP_VLU_DIS_XS_Y(1),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(1),	L_HELP_VLU_DIS_XS_Y(2),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
};


//=====================================================================================================================
//========================================[16头]===[3.托盘序号的描述指针]================================================
//=====================================================================================================================
//                              		左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_VLU_INDEX_DIS_X(I) 	(65  + I*(150) + I/1*18     +(I/4)*18)//X
#define L_WEIGHT_VLU_INDEX_DIS_Y(I) 	(115 + I*(210) + (I/1)*31   + 0)//Y
#define L_WEIGHT_VLU_INDEX_DIS_COLOR	(0x6494)//颜色
#define L_WEIGHT_VLU_INDEX_DIS_SIZE		(0x0016)//字库+字体大小
#define L_WEIGHT_VLU_INDEX_DIS_DQZWS	(0x0202)//对齐+整数位数
#define L_WEIGHT_VLU_INDEX_DIS_XWSLX	(0x0000)//小数位数+变量类型
appScreenDpCfg_Type ES_16H_WeightIndex_DP_Vlu[16]=
{
//  x坐标    						y坐标      				 		 背景颜色      			 		 字库+字体大小			  		   对齐+整数位数    			   小数位数+变量类型
	{L_WEIGHT_VLU_INDEX_DIS_X(0),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(0),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(1),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(1),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(2),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(2),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(3),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(3),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(4),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(4),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(5),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(5),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(6),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(6),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(7),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(7),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
};


//=====================================================================================================================
//========================================[16头]===[4.托盘背景色的描述指针]==============================================
//=====================================================================================================================
//                              	左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_COLOR_DIS_X(I) 	(11 + I*(150) + I/1*18 	 +(I/4)*18)//X
#define L_WEIGHT_COLOR_DIS_Y(I) 	(95 + I*(210) + (I/1)*31 + 0)//Y
appScreenDpColorCfg_Type ES_16H_WeightColor_DP_Vlu[16]=
{
//  x坐标    					y坐标      					   	
	{L_WEIGHT_COLOR_DIS_X(0),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(0),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(1),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(1),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(2),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(2),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(3),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(3),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(4),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(4),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(5),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(5),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(6),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(6),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(7),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(7),	L_WEIGHT_COLOR_DIS_Y(1)},
};

//
appScreenCfg_Type externalScreenCfg[APPSCREEN_WEIGHT_NUM_MAX]={
	//APPSCREEN_WEIGHT_NUM_6
	{
		6,
		ES_WeightVlu_DP_Add,
		ES_8H_WeightVlue_DP_Vlu_WuXiaoShu,
		ES_8H_WeightVlue_DP_Vlu_YouXiaoShu,
		\
		12,
		ES_HelpVlu_DP_Add,
		ES_8H_HelpVlue_DP_Vlu_WuXiaoShu,
		ES_8H_HelpVlue_DP_Vlu_YouXiaoShu,
		\
		6,
		ES_WeightIndex_DP_Add,
		ES_8H_WeightIndex_DP_Vlu,
		\
		6,
		ES_WeightColor_DP_Add,
		ES_8H_WeightColor_DP_Vlu,
	},

	//APPSCREEN_WEIGHT_NUM_8
	{
		8,
		ES_WeightVlu_DP_Add,
		ES_8H_WeightVlue_DP_Vlu_WuXiaoShu,
		ES_8H_WeightVlue_DP_Vlu_YouXiaoShu,
		\
		12,
		ES_HelpVlu_DP_Add,
		ES_8H_HelpVlue_DP_Vlu_WuXiaoShu,
		ES_8H_HelpVlue_DP_Vlu_YouXiaoShu,
		\
		8,
		ES_WeightIndex_DP_Add,
		ES_8H_WeightIndex_DP_Vlu,
		\
		8,
		ES_WeightColor_DP_Add,
		ES_8H_WeightColor_DP_Vlu,
	},

	//APPSCREEN_WEIGHT_NUM_12
	{
		12,
		ES_WeightVlu_DP_Add,
		ES_8H_WeightVlue_DP_Vlu_WuXiaoShu,
		ES_8H_WeightVlue_DP_Vlu_YouXiaoShu,
		\
		12,
		ES_HelpVlu_DP_Add,
		ES_8H_HelpVlue_DP_Vlu_WuXiaoShu,
		ES_8H_HelpVlue_DP_Vlu_YouXiaoShu,
		\
		12,
		ES_WeightIndex_DP_Add,
		ES_8H_WeightIndex_DP_Vlu,
		\
		12,
		ES_WeightColor_DP_Add,
		ES_16H_WeightColor_DP_Vlu,
	},

	//APPSCREEN_WEIGHT_NUM_16
	{
		16,
		ES_WeightVlu_DP_Add,
		ES_8H_WeightVlue_DP_Vlu_WuXiaoShu,
		ES_8H_WeightVlue_DP_Vlu_YouXiaoShu,
		\
		12,
		ES_HelpVlu_DP_Add,
		ES_8H_HelpVlue_DP_Vlu_WuXiaoShu,
		ES_8H_HelpVlue_DP_Vlu_YouXiaoShu,
		\
		16,
		ES_WeightIndex_DP_Add,
		ES_8H_WeightIndex_DP_Vlu,
		\
		16,
		ES_WeightColor_DP_Add,
		ES_16H_WeightColor_DP_Vlu,
	},
};
