/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "typedefine.h"
#include "app_t5l_ctrl.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

//=====================================================================================================================
//屏幕的描述指针地址范围：
//0x9010~0x9100：重量显示控件
//0x9110~0x9160：帮助信息的差值显示控件
//0x9210~0x9300：托盘序号显示控件
//0x9310~0x9400：托盘背景色显示控件
//=====================================================================================================================



//=====================================================================================================================
//=====================================================[15.6寸 16头]===================================================
//=====================================================================================================================
INT16 describlePointWeightVluAdd_Larger[T5L_MAX_CHANEL_LEN]={0x9011,0x9021,0x9031,0x9041,0x9051,0x9061,0x9071,0x9081,0x9091,0x90A1,0x90B1,0x90C1,0x90D1,0x90E1,0x90F1,0x9101};
INT16 describlePointWeightIndexAdd_Larger[T5L_MAX_CHANEL_LEN]={0x9211,0x9221,0x9231,0x9241,0x9251,0x9261,0x9271,0x9281,0x9291,0x92A1,0x92B1,0x92C1,0x92D1,0x92E1,0x92F1,0x9301};
INT16 describlePointHelpVluAdd_Larger[T5L_L_HELP_TOTAL_NUM]={0x9111,0x9121,0x9131,0x9141,0x9151,0x9161};
INT16 describlePointWeightColorAdd_Larger[T5L_MAX_CHANEL_LEN]={0x9311,0x9321,0x9331,0x9341,0x9351,0x9361,0x9371,0x9381,0x9391,0x93A1,0x93B1,0x93C1,0x93D1,0x93E1,0x93F1,0x9401};
//=====================================================================================================================
//=====================================================[15.6寸 8头]====================================================
//=====================================================================================================================
INT16 describlePointWeightVluAdd_Larger_8[HX711_CHANEL_NUM]={0x9411,0x9421,0x9431,0x9441,0x9451,0x9461,0x9471,0x9481};
INT16 describlePointWeightIndexAdd_Larger_8[HX711_CHANEL_NUM]={0x9611,0x9621,0x9631,0x9641,0x9651,0x9661,0x9671,0x9681};
INT16 describlePointHelpVluAdd_Larger_8[DIFF_TO_DIWEN_DATA_LEN]={0xA011,0xA021,0xA031,0xA041,0xA051,0xA061,0xA071,0xA081,0xA091,0xA0A1,0xA0B1,0xA0C1};
INT16 describlePointWeightColorAdd_Larger_8[HX711_CHANEL_NUM]={0x9711,0x9721,0x9731,0x9741,0x9751,0x9761,0x9771,0x9781};


//=====================================================================================================================
//=====================================================[15.6寸 16头]===================================================
//=====================================================================================================================
//=============================================15.6寸屏16头的【托盘重量-不带小数点】描述指针==============================
//                              左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_VLU_DIS_X(I) 	(19  + I*(150) + I/1*18     +(I/4)*18)//X position
#define L_WEIGHT_VLU_DIS_Y(I) 	(200 + I*(210) + (I/1)*31   + 0)//Y position
#define L_WEIGHT_VLU_DIS_COLOR	(0x6474)//color
#define L_WEIGHT_VLU_DIS_SIZE	(0x0020)//字库(00:0号字库)+字体大小(20:32大小)
#define L_WEIGHT_VLU_DIS_DQZWS	(0x0204)//对齐(00:左对齐，01:右对齐，02:居中) + 整数位数(04:4位整数)
#define L_WEIGHT_VLU_DIS_XWSLX	(0x0001)//小数位数(00:无小数，01:1位小数)+变量类型(01:长整型4字节)
INT16 describlePointWeightVluWuXiaoShu_Larger[T5L_MAX_CHANEL_LEN][6]=
{
//  x    					y      					颜色      				字库+字体大小			 对齐+整数位数    			   小数位数 变量类型
	{L_WEIGHT_VLU_DIS_X(0),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(0),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(1),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(1),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(2),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(2),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(3),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(3),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(4),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(4),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(5),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(5),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(6),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(6),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(7),	L_WEIGHT_VLU_DIS_Y(0),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
	{L_WEIGHT_VLU_DIS_X(7),	L_WEIGHT_VLU_DIS_Y(1),	L_WEIGHT_VLU_DIS_COLOR,	L_WEIGHT_VLU_DIS_SIZE,	L_WEIGHT_VLU_DIS_DQZWS,		L_WEIGHT_VLU_DIS_XWSLX},
};

//=============================================15.6寸屏16头的【托盘重量-带小数点】描述指针===============================
//                              左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_VLU_DIS_XS_X(I) 	(19  + I*(150) + I/1*18     +(I/4)*18)//X position
#define L_WEIGHT_VLU_DIS_XS_Y(I) 	(200 + I*(210) + (I/1)*31   + 0)//Y position
#define L_WEIGHT_VLU_DIS_XS_COLOR	(0x6474)//颜色
#define L_WEIGHT_VLU_DIS_XS_SIZE	(0x0032)//字库+字体大小
#define L_WEIGHT_VLU_DIS_XS_DQZWS	(0x0204)//对齐+整数位数
#define L_WEIGHT_VLU_DIS_XS_XWSLX	(0x0101)//小数位数+变量类型
INT16 describlePointWeightVluYouXiaoShu_Larger[T5L_MAX_CHANEL_LEN][6]=
{
//  x    					y      						颜色      				  字库+字体大小				 对齐+整数位数    			  小数位数 变量类型
	{L_WEIGHT_VLU_DIS_XS_X(0),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(0),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(1),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(1),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(2),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(2),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(3),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(3),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(4),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(4),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(5),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(5),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(6),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(6),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(7),L_WEIGHT_VLU_DIS_XS_Y(0),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
	{L_WEIGHT_VLU_DIS_XS_X(7),L_WEIGHT_VLU_DIS_XS_Y(1),	L_WEIGHT_VLU_DIS_XS_COLOR,L_WEIGHT_VLU_DIS_XS_SIZE,	L_WEIGHT_VLU_DIS_XS_DQZWS,	L_WEIGHT_VLU_DIS_XS_XWSLX},
};

//=============================================15.6寸屏16头的【托盘序号】描述指针========================================
//                              		左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_VLU_INDEX_DIS_X(I) 	(65  + I*(150) + I/1*18     +(I/4)*18)//X
#define L_WEIGHT_VLU_INDEX_DIS_Y(I) 	(115 + I*(210) + (I/1)*31   + 0)//Y
#define L_WEIGHT_VLU_INDEX_DIS_COLOR	(0x6494)//颜色
#define L_WEIGHT_VLU_INDEX_DIS_SIZE		(0x0016)//字库+字体大小
#define L_WEIGHT_VLU_INDEX_DIS_DQZWS	(0x0202)//对齐+整数位数
#define L_WEIGHT_VLU_INDEX_DIS_XWSLX	(0x0000)//小数位数+变量类型
INT16 describlePointWeightIndex_Larger[T5L_MAX_CHANEL_LEN][6]=
{
//  x    							y      							颜色      						字库+字体大小					 对齐+整数位数    				  小数位数 变量类型(00:整数2字节，01:长整数4字节)
	{L_WEIGHT_VLU_INDEX_DIS_X(0),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(0),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(1),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(1),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(2),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(2),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(3),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(3),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(4),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(4),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(5),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(5),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(6),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(6),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(7),	L_WEIGHT_VLU_INDEX_DIS_Y(0),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L_WEIGHT_VLU_INDEX_DIS_X(7),	L_WEIGHT_VLU_INDEX_DIS_Y(1),	L_WEIGHT_VLU_INDEX_DIS_COLOR,	L_WEIGHT_VLU_INDEX_DIS_SIZE,	L_WEIGHT_VLU_INDEX_DIS_DQZWS,	L_WEIGHT_VLU_INDEX_DIS_XWSLX},
};

//=============================================15.6寸屏16头的【帮助差值-不带小数点】描述指针==============================
//                              左边框 	单个宽度   	   单个间距	  	  (8+8)分块间距
#define L_HELP_VLU_DIS_X(I) 	(310  + I*(430-12) 	+ I/1*0     	+(I/4)*0)//X
#define L_HELP_VLU_DIS_Y(I) 	(580  + I*(637-571) + (I/1)*(15)   	+ 0)//Y
#define L_HELP_VLU_DIS_COLOR	(0xF810)//颜色
#define L_HELP_VLU_DIS_SIZE		(0x0022)//字库+字体大小
#define L_HELP_VLU_DIS_DQZWS	(0x0204)//对齐+整数位数
#define L_HELP_VLU_DIS_XWSLX	(0x0002)//小数位数+变量类型
INT16 describlePointHelpVluWuXiaoShu_Larger[T5L_L_HELP_TOTAL_NUM][6]=
{
//  x    					y      					颜色      				字库+字体大小			  对齐+整数位数    		  小数位数 变量类型
	{L_HELP_VLU_DIS_X(0),	L_HELP_VLU_DIS_Y(0),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(0),	L_HELP_VLU_DIS_Y(1),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(0),	L_HELP_VLU_DIS_Y(2),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(1),	L_HELP_VLU_DIS_Y(0),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(1),	L_HELP_VLU_DIS_Y(1),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
	{L_HELP_VLU_DIS_X(1),	L_HELP_VLU_DIS_Y(2),	L_HELP_VLU_DIS_COLOR,	L_HELP_VLU_DIS_SIZE,	L_HELP_VLU_DIS_DQZWS,	L_HELP_VLU_DIS_XWSLX},
};

//=============================================15.6寸屏16头的【帮助差值-带小数点】描述指针================================
#define L_HELP_VLU_DIS_XS_X(I) 	(I*(450+18)+28)//X
#define L_HELP_VLU_DIS_XS_Y(I) 	(I*(500+18)+115)//Y
#define L_HELP_VLU_DIS_XS_COLOR	(0x6474)//颜色
#define L_HELP_VLU_DIS_XS_SIZE	(0x0010)//字库+字体大小
#define L_HELP_VLU_DIS_XS_DQZWS	(0x0202)//对齐+整数位数
#define L_HELP_VLU_DIS_XS_XWSLX	(0x0002)//小数位数+变量类型
INT16 describlePointHelpVluYouXiaoShu_Larger[T5L_L_HELP_TOTAL_NUM][6]=
{
//  x    					y      					颜色      				字库+字体大小			对齐+整数位数    		小数位数 变量类型
	{L_HELP_VLU_DIS_XS_X(0),	L_HELP_VLU_DIS_XS_Y(0),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(0),	L_HELP_VLU_DIS_XS_Y(1),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(0),	L_HELP_VLU_DIS_XS_Y(2),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(1),	L_HELP_VLU_DIS_XS_Y(0),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(1),	L_HELP_VLU_DIS_XS_Y(1),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
	{L_HELP_VLU_DIS_XS_X(1),	L_HELP_VLU_DIS_XS_Y(2),	L_HELP_VLU_DIS_XS_COLOR,	L_HELP_VLU_DIS_XS_SIZE,	L_HELP_VLU_DIS_XS_DQZWS,	L_HELP_VLU_DIS_XS_XWSLX},
};

//=============================================15.6寸屏16头的【托盘的背景色】描述指针=====================================
//                              	左边框 单个宽度   单个间距	  (8+8)分块间距
#define L_WEIGHT_COLOR_DIS_X(I) 	(11 + I*(150) + I/1*18 	 +(I/4)*18)//X
#define L_WEIGHT_COLOR_DIS_Y(I) 	(95 + I*(210) + (I/1)*31 + 0)//Y
INT16 describlePointWeightColor_Larger[T5L_MAX_CHANEL_LEN][2]=
{
//  x    						y      					   	
	{L_WEIGHT_COLOR_DIS_X(0),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(0),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(1),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(1),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(2),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(2),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(3),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(3),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(4),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(4),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(5),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(5),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(6),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(6),	L_WEIGHT_COLOR_DIS_Y(1)},
	{L_WEIGHT_COLOR_DIS_X(7),	L_WEIGHT_COLOR_DIS_Y(0)},
	{L_WEIGHT_COLOR_DIS_X(7),	L_WEIGHT_COLOR_DIS_Y(1)},
};



//=====================================================================================================================
//=====================================================[15.6寸 8头]====================================================
//=====================================================================================================================
//=============================================15.6寸屏8头的【托盘重量-不带小数点】描述指针================================
//                              左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_VLU_DIS_X(I) 	(43  + I*(325) + I/1*12     +(I/4)*0)//X position
#define L8_WEIGHT_VLU_DIS_Y(I) 	(183 + I*(180) + (I/1)*12   + 0)//Y position
#define L8_WEIGHT_VLU_DIS_COLOR	(0x6474)//蓝色(0x041F)//color
#define L8_WEIGHT_VLU_DIS_SIZE	(0x0040)//字库(00:0号字库)+字体大小(20:32大小)
#define L8_WEIGHT_VLU_DIS_DQZWS	(0x0204)//对齐(00:左对齐，01:右对齐，02:居中) + 整数位数(04:4位整数)
#define L8_WEIGHT_VLU_DIS_XWSLX	(0x0001)//小数位数(00:无小数，01:1位小数)+变量类型(01:长整型4字节)
INT16 describlePointWeightVluWuXiaoShu_Larger_8[HX711_CHANEL_NUM][6]=
{
//  x    					y      					颜色      				字库+字体大小			 对齐+整数位数    			   小数位数 变量类型
	{L8_WEIGHT_VLU_DIS_X(0),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(0),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(1),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(1),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(2),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(2),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(3),	L8_WEIGHT_VLU_DIS_Y(0),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
	{L8_WEIGHT_VLU_DIS_X(3),	L8_WEIGHT_VLU_DIS_Y(1),	L8_WEIGHT_VLU_DIS_COLOR,	L8_WEIGHT_VLU_DIS_SIZE,	L8_WEIGHT_VLU_DIS_DQZWS,		L8_WEIGHT_VLU_DIS_XWSLX},
};

//=============================================15.6寸屏8头的【托盘重量-带小数点】描述指针==================================
//                              左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_VLU_DIS_XS_X(I) 	(46  + I*(325) + I/1*12     +(I/4)*0)//X position
#define L8_WEIGHT_VLU_DIS_XS_Y(I) 	(197 + I*(180) + (I/1)*12   + 0)//Y position
#define L8_WEIGHT_VLU_DIS_XS_COLOR	(0x6474)//颜色
#define L8_WEIGHT_VLU_DIS_XS_SIZE	(0x0028)//字库+字体大小
#define L8_WEIGHT_VLU_DIS_XS_DQZWS	(0x0204)//对齐+整数位数
#define L8_WEIGHT_VLU_DIS_XS_XWSLX	(0x0101)//小数位数+变量类型
INT16 describlePointWeightVluYouXiaoShu_Larger_8[HX711_CHANEL_NUM][6]=
{
//  x    					y      						颜色      				  字库+字体大小				 对齐+整数位数    			  小数位数 变量类型
	{L8_WEIGHT_VLU_DIS_XS_X(0),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(0),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(1),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(1),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(2),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(2),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(3),L8_WEIGHT_VLU_DIS_XS_Y(0),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
	{L8_WEIGHT_VLU_DIS_XS_X(3),L8_WEIGHT_VLU_DIS_XS_Y(1),	L8_WEIGHT_VLU_DIS_XS_COLOR,L8_WEIGHT_VLU_DIS_XS_SIZE,	L8_WEIGHT_VLU_DIS_XS_DQZWS,	L8_WEIGHT_VLU_DIS_XS_XWSLX},
};

//=============================================15.6寸屏8头的【托盘序号】描述指针==========================================
//                              		左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_VLU_INDEX_DIS_X(I) 	(160  + I*(325) + I/1*12     +(I/4)*0)//X
#define L8_WEIGHT_VLU_INDEX_DIS_Y(I) 	(139 + I*(180) + (I/1)*12   + 0)//Y
#define L8_WEIGHT_VLU_INDEX_DIS_COLOR	(0x0000)//颜色0x6494
#define L8_WEIGHT_VLU_INDEX_DIS_SIZE	(0x0012)//字库+字体大小
#define L8_WEIGHT_VLU_INDEX_DIS_DQZWS	(0x0202)//对齐+整数位数
#define L8_WEIGHT_VLU_INDEX_DIS_XWSLX	(0x0000)//小数位数+变量类型
INT16 describlePointWeightIndex_Larger_8[HX711_CHANEL_NUM][6]=
{
//  x    							y      							颜色      						字库+字体大小					 对齐+整数位数    				  小数位数 变量类型(00:整数2字节，01:长整数4字节)
	{L8_WEIGHT_VLU_INDEX_DIS_X(0),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(0),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(1),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(1),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(2),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(2),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(3),	L8_WEIGHT_VLU_INDEX_DIS_Y(0),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
	{L8_WEIGHT_VLU_INDEX_DIS_X(3),	L8_WEIGHT_VLU_INDEX_DIS_Y(1),	L8_WEIGHT_VLU_INDEX_DIS_COLOR,	L8_WEIGHT_VLU_INDEX_DIS_SIZE,	L8_WEIGHT_VLU_INDEX_DIS_DQZWS,	L8_WEIGHT_VLU_INDEX_DIS_XWSLX},
};

//=============================================15.6寸屏8头的【帮助差值-不带小数点】描述指针================================
//                              左边框 	单个宽度   	   单个间距	  	  (8+8)分块间距
#define L8_HELP_VLU_DIS_X(I) 	(0  + (I%3)*(100) 	+ (I%3)/2*60    +(I/3)*443)//X
#define L8_HELP_VLU_DIS_Y(I) 	(552 + I*(85) + (I/1)*(15)   	+ 0)//Y
#define L8_HELP_VLU_DIS_COLOR	(0xF810)//差值颜色
#define L8_HELP_VLU_DIS_COLOR_S	(0x0000)//被减数序号颜色
#define L8_HELP_VLU_DIS_COLOR_S2 (0x041F)//减数序号颜色
#define L8_HELP_VLU_DIS_SIZE	(0x0022)//字库+字体大小
#define L8_HELP_VLU_DIS_DQZWS	(0x0204)//对齐+整数位数
#define L8_HELP_VLU_DIS_XWSLX	(0x0000)//小数位数+变量类型
INT16 describlePointHelpVluWuXiaoShu_Larger_8[DIFF_TO_DIWEN_DATA_LEN][6]=
{
//  x    					y      					颜色      				字库+字体大小			  对齐+整数位数    		  小数位数 变量类型
	{L8_HELP_VLU_DIS_X(0),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(1),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(2),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(0),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(1),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(2),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(3),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(4),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(5),	L8_HELP_VLU_DIS_Y(0),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(3),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(4),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR_S2,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
	{L8_HELP_VLU_DIS_X(5),	L8_HELP_VLU_DIS_Y(1),	L8_HELP_VLU_DIS_COLOR,	L8_HELP_VLU_DIS_SIZE,	L8_HELP_VLU_DIS_DQZWS,	L8_HELP_VLU_DIS_XWSLX},
};

//=============================================15.6寸屏8头的【帮助差值-带小数点】描述指针===================================
//#define L8_HELP_VLU_DIS_XS_X(I) 	(0  + (I%3)*(110) 	+ (I%3)/2*60    +(I/3)*450)//X
#define L8_HELP_VLU_DIS_XS_X(I) 	(5  +  (I%6==1)*110 + (I%6==2)*250 + (I%6==3)*450 + (I%6==4)*560 + (I%6==5)*700)
#define L8_HELP_VLU_DIS_XS_Y(I) 	(552 + I*(85) + (I/1)*(15)   	+ 0)//Y
#define L8_HELP_VLU_DIS_XS_COLOR	(0xF810)//差值颜色
#define L8_HELP_VLU_DIS_XS_COLOR_S	(0x0000)//被减数序号颜色
#define L8_HELP_VLU_DIS_XS_COLOR_S2 (0x041F)//减数序号颜色
#define L8_HELP_VLU_DIS_XS_SIZE		(0x001C)//字库+字体大小
#define L8_HELP_VLU_DIS_XS_SIZE_S	(0x001C)//字库+字体大小
#define L8_HELP_VLU_DIS_XS_DQZWS	(0x0204)//对齐+整数位数
#define L8_HELP_VLU_DIS_XS_XWSLX1	(0x0000)//小数位数+变量类型
#define L8_HELP_VLU_DIS_XS_XWSLX	(0x0100)//小数位数+变量类型
INT16 describlePointHelpVluYouXiaoShu_Larger_8[DIFF_TO_DIWEN_DATA_LEN][6]=
{
//  x    					y      					颜色      				字库+字体大小			  对齐+整数位数    		  小数位数 变量类型
	{L8_HELP_VLU_DIS_XS_X(0),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(1),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(2),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
	{L8_HELP_VLU_DIS_XS_X(0),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(1),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(2),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
	{L8_HELP_VLU_DIS_XS_X(3),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(4),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(5),	L8_HELP_VLU_DIS_XS_Y(0),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
	{L8_HELP_VLU_DIS_XS_X(3),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(4),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR_S2,	L8_HELP_VLU_DIS_XS_SIZE,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX1},
	{L8_HELP_VLU_DIS_XS_X(5),	L8_HELP_VLU_DIS_XS_Y(1),	L8_HELP_VLU_DIS_XS_COLOR,	L8_HELP_VLU_DIS_XS_SIZE_S,	L8_HELP_VLU_DIS_XS_DQZWS,	L8_HELP_VLU_DIS_XS_XWSLX},
};

//=============================================15.6寸屏8头的【托盘的背景色】描述指针========================================
//                              	左边框 单个宽度   单个间距	  (8+8)分块间距
#define L8_WEIGHT_COLOR_DIS_X(I) 	(16 + I*(325) + I/1*12 	 +(I/4)*0)//X
#define L8_WEIGHT_COLOR_DIS_Y(I) 	(126 + I*(180) + (I/1)*12 + 0)//Y
INT16 describlePointWeightColor_Larger_8[HX711_CHANEL_NUM][2]=
{
//  x    						y      					   	
	{L8_WEIGHT_COLOR_DIS_X(0),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(0),	L8_WEIGHT_COLOR_DIS_Y(1)},
	{L8_WEIGHT_COLOR_DIS_X(1),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(1),	L8_WEIGHT_COLOR_DIS_Y(1)},
	{L8_WEIGHT_COLOR_DIS_X(2),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(2),	L8_WEIGHT_COLOR_DIS_Y(1)},
	{L8_WEIGHT_COLOR_DIS_X(3),	L8_WEIGHT_COLOR_DIS_Y(0)},
	{L8_WEIGHT_COLOR_DIS_X(3),	L8_WEIGHT_COLOR_DIS_Y(1)},
};









//=============================================8.8寸屏的【托盘的重量】描述指针=============================================
//屏幕的描述指针：显示托盘的重量控件
INT16 describlePointAdd[HX711_CHANEL_NUM]={0x9011,0x9021,0x9031,0x9041,0x9051,0x9061,0x9071,0x9081};
//托盘的重量显示：不带小数点显示
INT16 describlePointVluWuXiaoShu[HX711_CHANEL_NUM][6]=
{
//       x    	y      		颜色      	字库/字体大小	 对齐 整数位数    小数位数 变量类型
	{0x0056, 	0x0060, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x0056, 	0x0149, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x01DC, 	0x0060, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x01DC, 	0x0149, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x0362, 	0x0060, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x0362, 	0x0149, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x04E8, 	0x0060, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x04E8, 	0x0149, 	0x6474,		0x003C,			0x0204,			0x0001},
};
//托盘的重量显示：带小数点显示
INT16 describlePointVluXiaoShu[HX711_CHANEL_NUM][6]=
{
//       x    	y      		颜色      	字库/字体大小	 对齐 整数位数    小数位数 变量类型
	{0x0056, 	0x0077, 	0x6474,		0x0028,			0x0204,			0x0101},
	{0x0056, 	0x0160, 	0x6474,		0x0028,			0x0204,			0x0101},
	{0x01DC, 	0x0077, 	0x6474,		0x0028,			0x0204,			0x0101},
	{0x01DC, 	0x0160, 	0x6474,		0x0028,			0x0204,			0x0101},
	{0x0362, 	0x0077, 	0x6474,		0x0028,			0x0204,			0x0101},
	{0x0362, 	0x0160, 	0x6474,		0x0028,			0x0204,			0x0101},
	{0x04E8, 	0x0077, 	0x6474,		0x0028,			0x0204,			0x0101},
	{0x04E8, 	0x0160, 	0x6474,		0x0028,			0x0204,			0x0101},
};

//================================================================================================
//屏幕的描述指针：托盘序号控件
INT16 describleIndexPointAdd[HX711_CHANEL_NUM]={0x9211,0x9221,0x9231,0x9241,0x9251,0x9261,0x9271,0x9281};
INT16 describleIndexPointData[HX711_CHANEL_NUM][6]=
{
//       x    	y      		颜色      	字库/字体大小	 对齐 整数位数    小数位数 变量类型
	{0x00BC, 	0x0017, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x00BC, 	0x0109, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x0241, 	0x0017, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x0241, 	0x0109, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x03C7, 	0x0017, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x03C7, 	0x0109, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x054D, 	0x0017, 	0x6474,		0x003C,			0x0204,			0x0001},
	{0x054D, 	0x0109, 	0x6474,		0x003C,			0x0204,			0x0001},
};

//================================================================================================
//屏幕的描述指针：帮助信息控件
#define DESCRIBLE_POINT_HELP_COLOR			(0XF810)//红色
#define DESCRIBLE_POINT_HELP_X_POS			(0X06E4)//1764
#define DESCRIBLE_POINT_HELP_WU_XIAOSHU		(0X001A)//0号字库 字体大小26
#define DESCRIBLE_POINT_HELP_YOU_XIAOSHU	(0X0014)//0号字库 字体大小20
//帮助信息：不带小数显示
INT16 describlePointAdd_help[DESCRIBLE_POINT_HELP_NUM]={0x9111,0x9121,0x9131,0x9141};
INT16 describlePointVluWuXiaoShu_help[DESCRIBLE_POINT_HELP_NUM][6]=
{
//       x    	y      		颜色      	字库/字体大小	 对齐 整数位数    小数位数 变量类型
	{DESCRIBLE_POINT_HELP_X_POS, 	97, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_WU_XIAOSHU,			0x0204,			0x0000},
	{DESCRIBLE_POINT_HELP_X_POS, 	167, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_WU_XIAOSHU,			0x0204,			0x0000},
	{DESCRIBLE_POINT_HELP_X_POS, 	232, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_WU_XIAOSHU,			0x0204,			0x0000},
	{DESCRIBLE_POINT_HELP_X_POS, 	303, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_WU_XIAOSHU,			0x0204,			0x0000},
};
//帮助信息：带小数显示
INT16 describlePointVluXiaoShu_help[DESCRIBLE_POINT_HELP_NUM][6]=
{
//       x    	y      		颜色      	字库/字体大小	 对齐 整数位数    小数位数 变量类型
	{DESCRIBLE_POINT_HELP_X_POS, 	105, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_YOU_XIAOSHU,			0x0204,			0x0100},
	{DESCRIBLE_POINT_HELP_X_POS, 	175, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_YOU_XIAOSHU,			0x0204,			0x0100},
	{DESCRIBLE_POINT_HELP_X_POS, 	240, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_YOU_XIAOSHU,			0x0204,			0x0100},
	{DESCRIBLE_POINT_HELP_X_POS, 	310, 	DESCRIBLE_POINT_HELP_COLOR,		DESCRIBLE_POINT_HELP_YOU_XIAOSHU,			0x0204,			0x0100},
};
